name: words_env
channels:
  - conda-forge
dependencies:
  - python=3.10  # or any compatible version
  - openai
  - jupyter
  - pandas
  - scikit-learn
  - matplotlib
  - tqdm
  - plotly
  - numpy
  - gensim
  - jupyter-dash
  - pip:
      - requests
      - SQLAlchemy
